"""Initial migration.

Revision ID: 215c32b068de
Revises: 
Create Date: 2022-05-02 02:45:33.722570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215c32b068de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoomTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RoomType_Service',
    sa.Column('roomType_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roomType_id'], ['RoomTypes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['Services.id'], )
    )
    op.create_table('Rooms',
    sa.Column('roomNumber', sa.Integer(), nullable=False),
    sa.Column('roomType_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roomType_id'], ['RoomTypes.id'], ),
    sa.PrimaryKeyConstraint('roomNumber')
    )
    op.create_table('Bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientName', sa.String(length=255), nullable=False),
    sa.Column('clientNumber', sa.String(length=255), nullable=False),
    sa.Column('checkinDate', sa.String(length=30), nullable=True),
    sa.Column('checkoutDate', sa.String(length=30), nullable=True),
    sa.Column('checkinTime', sa.String(length=30), nullable=True),
    sa.Column('checkoutTime', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('roomNumber', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roomNumber'], ['Rooms.roomNumber'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ServiceOrders',
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['Bookings.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['Services.id'], ),
    sa.PrimaryKeyConstraint('orderId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ServiceOrders')
    op.drop_table('Bookings')
    op.drop_table('Rooms')
    op.drop_table('RoomType_Service')
    op.drop_table('Services')
    op.drop_table('RoomTypes')
    # ### end Alembic commands ###
